import * as mongoose from 'mongoose';

export const InvoiceSchema = new mongoose.Schema({
    first_name_invoice: String,
    last_name_invoice: String,
    email_invoice: String,
    phone_invoice: String,
    address_invoice: String,
    description_invoice: String,
    opis_invoice: String,
    created_at: { type: Date, default: Date.now },
    product01_invoice: String,
    price01_invoice: String,
    product02_invoice: String,
    price02_invoice: String,
    product03_invoice: String,
    price03_invoice: String,
    product04_invoice: String,
    price04_invoice: String,
    product05_invoice: String,
    price05_invoice: String,
    product06_invoice: String,
    price06_invoice: String,
    product07_invoice: String,
    price07_invoice: String,
    product08_invoice: String,
    price08_invoice: String,
    product09_invoice: String,
    price09_invoice: String,
    product10_invoice: String,
    price10_invoice: String,
    payment_method_incoive: String,
    sum_invoice: String,
})